w10d1/tinyAppV2/config/routes.rb
Rails.application.routes.draw do

  # root 'cats#index'

  # # Example of a 'normal route'
  get 'about' => 'cats#index'

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats

end

w10d1/tinyAppV2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d1/tinyAppV2/app/models/cat.rb
class Cat < ApplicationRecord
end

w10d1/tinyAppV2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

w10d1/tinyAppV2/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @secretstuff = 'in ancient Egypt, cats were worshipped as powerful creatures.'
        @cats = Cat.all
    end

#     def show
#         @cat = Cat.find(params[:id])
#     end

#     def new

#     end

    def create
        render plain: params[:cat].inspect
    end

#     def create
# #        render plain: params[:cat].inspect
#         @cat = Cat.new(cat_params)
#         @cat.save
#         redirect_to @cat
#     end

#     private def cat_params
#         params.require(:cat).permit(:title, :body)
#     end

end

w10d1/tinyAppV2/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d1/tinyAppV2/app/helpers/cats_helper.rb
module CatsHelper
end

w10d1/tinyAppV2/app/views/cats/index.html.erb
<h1>Homepage!</h1>
<%= @secretstuff %>

<% @cats.each do |cat| %>
    <h3><%= cat.title %></h3>
    <p><%= cat.body %></p>
<% end %>

w10d1/tinyAppV2/app/views/cats/new.html.erb
<h1>Add Cat</h1>

<%= form_for :cat, url: cats_path do |f| %>
<p>
    <%= f.label :title %>
    <%= f.text_field :title %>    
</p>
<p>
    <%= f.label :body %>
    <%= f.text_area :body %>    
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

w10d1/tinyAppV2/app/views/cats/show.html.erb
<h2>
<%= @cat.title %>
</h2>

<p>
<%= @cat.body %>
</p>

w10d1/tinyAppV2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyAppV2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>